In [2]:
import numpy as np

We can create a numpy array by passing a sequence data type inside np.array() function adn we can create any diemnsional array we want

In [18]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.shape

(4,)

Creating a 2d array

In [15]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.shape

(2, 4)

Arrays are also mutable like lists

In [19]:
arr[0] = 100
arr

array([100,   2,   3,   4])

In [20]:
arr2[0][3] = 100
arr2

array([[  1,   2,   3, 100],
       [  5,   6,   7,   8]])

Slciing and indexing also can be done in an array

In [22]:
arr[-1]

4

In [25]:
arr[-1:-3:-1]

array([4, 3])

In [26]:
arr[1:-1]

array([2, 3])

In [27]:
arr2[1][2:]

array([7, 8])

Array is actually a collection of same data types, even when we take different dtaatypes, it will convert all into similar data types

In [28]:
arr3 = np.array([1, 2.3, 3+4j, 'PK'])
arr3

array(['1', '2.3', '(3+4j)', 'PK'], dtype='<U64')