We have seperately matrix assocaited functions to ease out operations involving matrix operations

In [1]:
import numpy as np

In [2]:
mat = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
mat

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [3]:
#we can find the transpose by using T attribute
trans = mat.T
trans

matrix([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

In [4]:
# To get identity matrix
id = np.eye(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# We can even pass shape
id2 = np.eye(3, 4)
id2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [6]:
#If we want a pure diagonal matrix
dgm = np.diag([10, 20, 30])
dgm

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [8]:
# for matrix multiplications
id @ dgm

array([[10.,  0.,  0.],
       [ 0., 20.,  0.],
       [ 0.,  0., 30.]])