All mathematical operatyions on arrays will be done element wise unlike lists

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30])
arr

array([10, 20, 30])

In [3]:
arr*3

array([30, 60, 90])

In [4]:
arr/10

array([1., 2., 3.])

lists take huge memory whereas arrays take less memory

In [5]:
my_list = [10, 20, 30]
import sys
sys.getsizeof(my_list)

88

In [6]:
arr.nbytes

12

If we observe above we took both same lsists, but list took huge siuze and arrays took very less size, this is because lists store meta data
, that is since these are not stored in continuous memory locatrions it stores where the next element locates and also the size of the 
present element etc

In fatc we can even specify the size of each element we want while defining the array itself

In [7]:
arr1 = np.array([1, 2, 3, 4], dtype = np.int8)
arr1

array([1, 2, 3, 4], dtype=int8)

In [8]:
arr1.nbytes

4

In [9]:
arr1.itemsize

1

We can check dimenison and shape of array by using ndim and shape attributes

In [10]:
arr0 = np.array(1)
arr0

array(1)

In [11]:
arr0.ndim

0

In [12]:
arr0.shape

()

In [13]:
aar1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4], dtype=int8)

In [14]:
arr1.ndim

1

In [15]:
arr1.shape

(4,)

In [16]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
list_3 = [[[1, 2, 3, 4], [3, 4, 5, 6]],
          [[5, 6, 6, 8], [7,8, 9, 8]]]
arr3 = np.array(list_3)
arr3

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[5, 6, 6, 8],
        [7, 8, 9, 8]]])

In [20]:
arr3.ndim

3

In [21]:
arr3.shape

(2, 2, 4)

We can create ndimensional array by using ndim argument

In [26]:
arr = np.array([1, 2, 3, 4], ndmin = 3)
arr

array([[[1, 2, 3, 4]]])

In [27]:
arr.ndim

3

In [28]:
arr.shape

(1, 1, 4)