In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
arr.ndim

1

In [5]:
#size gives us the no.of elements in an array
arr.size

4

In [6]:
arr.shape

(4,)

In [7]:
arr.itemsize

4

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr.nbytes

16

In [10]:
arr.max()

4

In [11]:
arr.min()

1

In [12]:
arr.sum()

10

In [13]:
arr.mean()

2.5

In [16]:
# we can even do sum, min, max, mean columns wise, for this i will take 2d array, axis = 0 top most one
arr2 = np.array([[1, 2,3, 4], [5, 6, 7, 8]])
arr2.min(axis = 0)

array([1, 2, 3, 4])

In [18]:
arr2.min(axis = 1)

array([1, 5])

In [27]:
arr3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [28]:
arr3.shape

(2, 3, 4)

In [29]:
arr3.min(axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
arr3.min(axis = 1)

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [31]:
arr3.min(axis = 2)

array([[ 1,  5,  9],
       [13, 17, 21]])