In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
arr.ndim

1

In [4]:
#size gives us the no.of elements in an array
arr.size

4

In [5]:
arr.shape

(4,)

In [6]:
arr.itemsize

4

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr.nbytes

16

In [9]:
arr.max()

4

In [10]:
arr.min()

1

In [11]:
arr.sum()

10

In [12]:
arr.mean()

2.5

In [13]:
# we can even do sum, min, max, mean columns wise, for this i will take 2d array, axis = 0 top most one
arr2 = np.array([[1, 2,3, 4], [5, 6, 7, 8]])
arr2.min(axis = 0)

array([1, 2, 3, 4])

In [14]:
arr2.min(axis = 1)

array([1, 5])

In [15]:
arr3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [16]:
arr3.shape

(2, 3, 4)

In [17]:
arr3.min(axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr3.min(axis = 1)

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [19]:
arr3.min(axis = 2)

array([[ 1,  5,  9],
       [13, 17, 21]])

In [20]:
arr

array([1, 2, 3, 4])

In [21]:
# we can even axis array multiple array elements like this
arr[[0, 0, 1, 2]]

array([1, 1, 2, 3])

In [22]:
# we can even assing multiple values at a time
arr[[0, 1]] = [0, 1]
arr

array([0, 1, 3, 4])

In [23]:
# we can even assign multiple indices to a single value
arr[[0, 1, 2, 3]] = 0
arr

array([0, 0, 0, 0])

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# we can access elements like this below
arr2[0][1]

2

In [26]:
#same as below
arr2[0, 1]

2

In [27]:
arr2[[0, 1], 1]

array([2, 6])

In [28]:
arr2[[0, 1], [1, 2]]

array([2, 7])

In [33]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# we can reshape it into (4, 2)
arr2.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
#by default it will follow c order first , that means reshaping first row and then second row
arr2.reshape(4, 2, order = 'c')

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
#This makes column wise order
arr2.reshape(4, 2, order = 'f')

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [40]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# boolean indexing, let's say if we want to replace all >5 values with some things we want
arr2 > 5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [43]:
mask = (arr2 > 5)

In [45]:
arr2[mask]

array([6, 7, 8])

In [46]:
arr2[mask] = 1

In [47]:
arr2

array([[1, 2, 3, 4],
       [5, 1, 1, 1]])

In [48]:
arr2[mask] = [0, 1, 2]
arr2

array([[1, 2, 3, 4],
       [5, 0, 1, 2]])