We can create random arrays by using random module

In [1]:
import numpy as np

In [11]:
arr0 = np.random.random()
arr0

0.26718716871772485

In [12]:
arr1 = np.random.random(3)
arr1

array([0.55252762, 0.82269344, 0.98129606])

In [13]:
arr1.ndim

1

In [14]:
arr1.shape

(3,)

In [15]:
arr2 = np.random.random((3, 5))
arr2

array([[0.45900873, 0.26799814, 0.21158288, 0.76883901, 0.22388686],
       [0.28071071, 0.33009541, 0.48118482, 0.50183244, 0.02128336],
       [0.30660434, 0.02812829, 0.4430811 , 0.65811439, 0.66659226]])

In [16]:
# We can also use rand module , but we can't pass tuple as shape, we will directly pass shape as integers
arr3 = np.random.rand(3, 4, 5)
arr3

array([[[0.85480139, 0.05938447, 0.46392864, 0.644336  , 0.87055881],
        [0.90524286, 0.43688648, 0.58495273, 0.41992299, 0.61579122],
        [0.55813518, 0.71340755, 0.64068891, 0.14132644, 0.65100513],
        [0.22107132, 0.16438327, 0.17235234, 0.4304169 , 0.62622402]],

       [[0.15065816, 0.8925002 , 0.03937036, 0.35888707, 0.57399906],
        [0.09428005, 0.16071554, 0.56449234, 0.77567958, 0.81055455],
        [0.13451038, 0.86133627, 0.87365701, 0.70122269, 0.91114133],
        [0.39703994, 0.11913204, 0.97793737, 0.51077072, 0.94911147]],

       [[0.61372092, 0.67088605, 0.46942156, 0.72471248, 0.27194719],
        [0.60786473, 0.22640568, 0.63988584, 0.8889562 , 0.39385657],
        [0.15254438, 0.79638232, 0.15561772, 0.46067999, 0.25311153],
        [0.1994559 , 0.34875352, 0.52489641, 0.12410751, 0.34904154]]])

In [17]:
#randn gives us values from standard normal diostribution where mean is 0 and variance is 1, so majority of the values are in between -3, 3
arrn = np.random.randn(3, 4)
arrn

array([[ 0.43586513,  0.5225603 , -0.83783701, -0.10872159],
       [ 0.09857818, -0.42963263, -0.05311183,  2.53571847],
       [-1.64176657, -0.51150863,  0.12295236,  0.48334809]])

In [18]:
array_int = np.random.randint(10, 20, (3, 4))
array_int

array([[10, 19, 15, 18],
       [13, 12, 17, 12],
       [17, 16, 15, 11]])

In [26]:
#Sometimes we want the same set of random numbers to use for our tests, we can do this by using seed function and everytime it runs with a 
# particlular seed value, same values will be formed
np.random.seed(100)
arr = np.random.randint(10, 100, (2, 3))
arr

array([[18, 34, 77],
       [97, 89, 58]])

In [27]:
arr

array([[18, 34, 77],
       [97, 89, 58]])

In [28]:
arr+2

array([[20, 36, 79],
       [99, 91, 60]])

In [31]:
# We can even select our choiced numbers from some data
arr = np.random.choice([12, 17, 186, 12])
arr

186

In [34]:
# we can even pass shape we want
arr = np.random.choice([12, 17, 186, 12], size = (2, 3))
arr

array([[186,  12, 186],
       [ 17, 186, 186]])

In [35]:
# we can even pass the weights we want for each number
arr = np.random.choice([12, 17, 186, 12], size = (2, 3), p = [1, 0, 0, 0])
arr

array([[12, 12, 12],
       [12, 12, 12]])

In [36]:
# Bothg shuffle and permuation will shuffle our set but shuffle mnodifies the array in place but permuation will return a copy
arr1 = np.array([1, 2, 3,4])
arr1

array([1, 2, 3, 4])

In [39]:
np.random.shuffle(arr1)
arr1

array([1, 3, 2, 4])

In [42]:
arr2 = np.random.permutation(arr1)
arr1

array([1, 3, 2, 4])

In [51]:
arr2

array([1, 2, 3, 4])